local Dialogs = {
    {
        Dialog = "I think grandma was cooking something.",
    },
    
    {
        Dialog = "Why does it look like that?",
        Delay = 5,
    },

    {
        Dialog = "*gulp*",
        Delay = 5
    },
    
    {
        Dialog = "Ugh...",
        Delay = 3
    },

    {
        Dialog = "I don't feel so good...",
        Delay = 3,
    },

    {
        Dialog = nil,
        Delay = 3
    }

}

return Dialogs