local Dialogs = {
    {
        Dialog = "What was that!?",
        Delay = 3
    },

    {
        Dialog = "Maybe grandma is back?",
        Delay = 4
    },

    {
        Dialog = "But grandma doesn't knock like that though...",
        Delay = 5
    },

    {
        Dialog = "I should check it out...",
        Delay = 5
    },

    {
        Dialog = nil,
        Delay = 5
    }
}

return Dialogs