local Dialogs = {
    {
        Dialog = "Oh, hi grandma.",
        Delay = 3
    },

    {
        Dialog = "Hello, dear.",
        Delay = 3,
        DialogColor = Color3.fromRGB(255, 230, 0)
    },

    {
        Dialog = "I forgot to leave you cookies.",
        Delay = 3,
        DialogColor = Color3.fromRGB(255, 230, 0)
    },
    
    {
        Dialog = "Here you go, dear",
        Delay = 5,
        DialogColor = Color3.fromRGB(255, 230, 0)
    },

    {
        Dialog = "Wow, thank you granny!",
        Delay = 3
    },

    {
        Dialog = nil,
        Delay = 6
    },

}

return Dialogs