local Dialogs = {}

Dialogs[1] = {
    Dialog = "Phew, I made it in time."
}

Dialogs[2] = {
    Dialog = "How can grandma live in such cold place all the time?",
    Delay = 5
}
Dialogs[3] = {
    Dialog = "If I had known this I would've turned the request down...",
    Delay = 5
}

Dialogs[4] = {
    Dialog = "Whatever. I'm gonna take a look around the house.",
    Delay = 5
}

Dialogs[5] = {
    Dialog = nil,
    Delay = 4
}

return Dialogs